const GOOD_LISTS = {
  DEFAULT_POSITIVE_MODIFIERS: [
  "masterpiece",
  "best quality",
  "high quality",
  "top quality",
  "highest quality",
  "ultra high quality",
  "very aesthetic",
  "aesthetic",
  "beautiful",
  "beautiful and aesthetic",
  "good",
  "great",
  "best",
  "beautiful",
  "newest",
  "2023",
  "2022",
  "2021",
  "depth of field",
  "DOF",
  "bokeh",
  "8k",
  "8k resolution",
  "8k wallpaper",
  "4k",
  "4k resolution",
  "UHD",
  "HD",
  "highres",
  "absurdres",
  "ultra high definition",
  "high definition",
  "detailed",
  "highly detailed",
  "very detailed",
  "extremely detailed",
  "ultra detailed",
  "incredibly detailed",
  "hyper detailed",
  "intricate",
  "intricate details",
  "finely detailed",
  "sharp focus",
  "in focus",
  "focused",
  "detailed shadows",
  "detailed background",
  "detailed clothing",
  "detailed eyes",
  "beautiful eyes",
  "vibrant colors",
  "vivid colors",
  "rich colors",
  "colorful",
  "bright colors",
  "volumetric",
  "god rays",
  "lens flare",
  "bloom",
  "ambient occlusion",
  "official",
  "dynamic",
  "detailed skin",
  "detailed skin texture",
  ]\n};

