const ALL_LISTS = {
  "presets": [
    {
      "id": "empty",
      "title": "Empty negative list",
      "items": [],
      "type": "negative"
    },
    {
      "id": "audio-bad",
      "title": "Poor preference data list",
      "items": [
        "Horrorcore",
        "Rockabilly",
        "Soundtrack",
        "kid's",
        "children's",
        "Christmas",
        "holiday",
        "jingle",
        "oldies",
        "Teen",
        "Vocaloid",
        "idol",
        "K-Pop",
        "mandarin",
        "LGBT",
        "Swing",
        "Country",
        "Anime",
        "Black Metal",
        "Straight Edge",
        "Psychobilly",
        "mediocre",
        "Parody",
        "humorous",
        "Comedy",
        "Reggaetón",
        "Drill",
        "Future Bass",
        "Big Room House",
        "Dubstep",
        "Bounce",
        "Hardstyle",
        "Trance",
        "Jersey Club",
        "Footwork",
        "Chiptune",
        "Psytrance",
        "Moombahton",
        "Riddim Dubstep",
        "Tech-House",
        "Phonk",
        "Electro-swing",
        "Cumbia",
        "Tango",
        "Bossa Nova",
        "Samba",
        "Dancehall",
        "Bhangra",
        "Disco",
        "Polka",
        "Vaporwave",
        "Minimal Techno",
        "Blues",
        "Sea Shanty",
        "Lo-fi Hip-Hop",
        "Synthwave",
        "K-pop",
        "christian",
        "islamic",
        "religious"
      ],
      "type": "negative"
    },
    {
      "id": "audio-quality-negative",
      "title": "Audio quality negative list",
      "items": [
        "clipping",
        "distorted",
        "overcompressed",
        "muddy mix",
        "background hiss",
        "static-laden",
        "crackling",
        "phasing issues",
        "mono-only",
        "low-bitrate",
        "flat dynamics",
        "harsh sibilance",
        "tinny",
        "aliasing",
        "compression artifacts",
        "pops",
        "clicks",
        "buzzing",
        "dull",
        "hollow",
        "thin",
        "out-of-tune",
        "timing errors",
        "glitchy",
        "warped",
        "muffled",
        "boomy bass",
        "shrill highs",
        "harsh mids",
        "dry",
        "brittle",
        "grainy",
        "coarse",
        "noisy",
        "narrow stereo image",
        "unnatural",
        "artificial",
        "inconsistent",
        "unbalanced",
        "blurred imaging",
        "resonant frequencies",
        "boxy",
        "nasal",
        "congested",
        "lifeless",
        "flat",
        "weak dynamics",
        "low-fidelity",
        "poor mastering",
        "poorly mixed",
        "unclear vocals",
        "uneven levels",
        "irritating",
        "unpleasant",
        "substandard",
        "amateurish",
        "incomplete",
        "inferior",
        "indistinct",
        "weak transient response",
        "muddled",
        "washed-out",
        "overly reverberant",
        "overly dry",
        "echo-heavy",
        "robotic",
        "metallic",
        "harsh",
        "grating",
        "fatiguing",
        "repetitive",
        "monotonous",
        "unrefined",
        "cheap-sounding",
        "lazy mix",
        "poorly balanced",
        "rough",
        "lifeless",
        "ineffective",
        "drab",
        "amateur-quality",
        "low-resolution",
        "disjointed",
        "sloppy",
        "carelessly produced",
        "irritating noise floor",
        "amateurish editing",
        "grungy",
        "distorted bass",
        "overly saturated",
        "badly equalized",
        "inferior compression",
        "muddy low-end",
        "poorly tuned",
        "forgettable",
        "mundane",
        "uninspiring",
        "terrible",
        "awful",
        "worst"
      ],
      "type": "negative"
    },
    {
      "id": "image-bad",
      "title": "Image negative list",
      "items": [
        "worst quality",
        "normal quality",
        "low quality",
        "low res",
        "old",
        "oldest",
        "blurry",
        "distortion",
        "extra digits",
        "cropped",
        "jpeg artifacts",
        "grainy",
        "pixelated",
        "sketch",
        "error",
        "duplicate",
        "ugly",
        "monochrome",
        "horror",
        "geometry",
        "disgusting",
        "mutation",
        "bad anatomy",
        "bad proportions",
        "bad quality",
        "deformed",
        "disconnected limbs",
        "out of frame",
        "out of focus",
        "dehydrated",
        "disfigured",
        "extra arms",
        "extra limbs",
        "extra hands",
        "fused fingers",
        "gross proportions",
        "long neck",
        "malformed limbs",
        "mutated",
        "mutated hands",
        "mutated limbs",
        "missing arms",
        "missing legs",
        "missing hand",
        "missing fingers",
        "poorly drawn face",
        "poorly drawn hands",
        "poorly drawn feet",
        "bad face",
        "bad hands",
        "ugly face",
        "asymmetrical",
        "fused face",
        "double face",
        "worst face",
        "worst quality",
        "worst face",
        "worst feet",
        "worst thigh",
        "three hands",
        "three legs",
        "three feet",
        "three thigh",
        "three crus",
        "extra crus",
        "fused crus",
        "extra legs",
        "extra fingers",
        "extra toes",
        "extra crus",
        "extra thigh",
        "fused feet",
        "fused thigh",
        "fused crus",
        "fused hands",
        "fused toes",
        "too many fingers",
        "too many toes",
        "long fingers",
        "oversized eyes",
        "huge eyes",
        "extra eyes",
        "cross-eyed",
        "imperfect eyes",
        "bad eyes",
        "day-glo",
        "high CFG artifact",
        "bad illustration",
        "bad composition",
        "malformed",
        "misshapen",
        "disproportioned",
        "gross proportions",
        "mutated body parts",
        "deformed body features",
        "dismembered",
        "amputee",
        "amputation",
        "disfigured",
        "morbid",
        "mutilated",
        "mutation",
        "mutated",
        "mutated hands",
        "mutated limbs",
        "distorted",
        "stretched",
        "conjoined",
        "floating limbs",
        "disconnected limbs",
        "unnatural pose",
        "unnatural",
        "unsightly",
        "unattractive",
        "split image",
        "tiling",
        "duplicated features",
        "cloned face",
        "duplicate",
        "watermark",
        "signature",
        "username",
        "autograph",
        "printed words",
        "text",
        "banner",
        "branding",
        "logo",
        "identifying mark",
        "geometry",
        "script",
        "UI",
        "interface",
        "low resolution",
        "low quality",
        "normal quality",
        "worst quality",
        "jpeg artifacts",
        "color aberration",
        "aberrations",
        "noise",
        "grainy",
        "hazy",
        "blurry",
        "unfocused",
        "underexposed",
        "overexposed",
        "low saturation",
        "oversaturated",
        "harsh lighting",
        "flash",
        "sketch",
        "drawing",
        "abstract",
        "surreal",
        "psychedelic",
        "kitsch",
        "rotten",
        "twisted"
      ],
      "type": "negative"
    },
    {
      "id": "empty",
      "title": "Empty positive list",
      "items": [],
      "type": "positive"
    },
    {
      "id": "image-positive",
      "title": "Image positive list",
      "items": [
        "masterpiece",
        "best quality",
        "high quality",
        "top quality",
        "highest quality",
        "ultra high quality",
        "very aesthetic",
        "aesthetic",
        "beautiful",
        "beautiful and aesthetic",
        "good",
        "great",
        "best",
        "beautiful",
        "newest",
        "2023",
        "2022",
        "2021",
        "depth of field",
        "DOF",
        "bokeh",
        "8k",
        "8k resolution",
        "8k wallpaper",
        "4k",
        "4k resolution",
        "UHD",
        "HD",
        "highres",
        "absurdres",
        "ultra high definition",
        "high definition",
        "detailed",
        "highly detailed",
        "very detailed",
        "extremely detailed",
        "ultra detailed",
        "incredibly detailed",
        "hyper detailed",
        "intricate",
        "intricate details",
        "finely detailed",
        "sharp focus",
        "in focus",
        "focused",
        "detailed shadows",
        "detailed background",
        "detailed clothing",
        "detailed eyes",
        "beautiful eyes",
        "vibrant colors",
        "vivid colors",
        "rich colors",
        "colorful",
        "bright colors",
        "volumetric",
        "god rays",
        "lens flare",
        "bloom",
        "ambient occlusion",
        "official",
        "dynamic",
        "detailed skin",
        "detailed skin texture"
      ],
      "type": "positive"
    },
    {
      "id": "general-audio",
      "title": "General audio positive list",
      "items": [
        "good",
        "best",
        "great",
        "wonderful",
        "amazing",
        "incredible",
        "stunning",
        "beautiful",
        "brilliant",
        "genius",
        "complex",
        "intricate",
        "layered",
        "lush",
        "expansive",
        "frisson",
        "powerful",
        "moving",
        "brought to tears by",
        "sublime",
        "breathtaking",
        "mesmerizing",
        "awe-inspiring",
        "evocative",
        "profound",
        "exquisite",
        "dazzling",
        "sensational",
        "haunting",
        "captivating",
        "enchanting",
        "masterful",
        "poignant",
        "spellbinding",
        "transcendent",
        "majestic",
        "ethereal",
        "phenomenal",
        "vibrant",
        "exhilarating",
        "radiant",
        "luminous",
        "stirring",
        "magnificent",
        "extraordinary",
        "unparalleled",
        "unforgettable",
        "transformative",
        "euphoric",
        "enthralling",
        "heartfelt",
        "soul-stirring",
        "groundbreaking",
        "iconic",
        "visionary",
        "astonishing",
        "compelling",
        "nuanced",
        "thought-provoking",
        "resonant",
        "cathartic",
        "thrilling",
        "expressive",
        "virtuosic",
        "electrifying",
        "tender",
        "graceful",
        "delicate",
        "vivid",
        "intricate",
        "imaginative",
        "emotive",
        "rapturous",
        "dynamic",
        "balanced",
        "immersive",
        "crystalline",
        "resonant",
        "lushly orchestrated",
        "harmonically rich",
        "sonorous",
        "pristine",
        "textured",
        "atmospheric",
        "detailed",
        "nuanced",
        "spatially expansive",
        "warm",
        "inviting",
        "enveloping",
        "engaging",
        "lifelike",
        "rhythmic",
        "percussive",
        "robust",
        "smooth",
        "velvety",
        "silky",
        "refined",
        "natural",
        "transparent",
        "punchy",
        "crisp",
        "vivid",
        "evocative",
        "spine-tingling",
        "goosebump-inducing",
        "emotionally charged",
        "deeply affecting",
        "blissful",
        "hypnotic",
        "melodic",
        "pulsating",
        "groovy",
        "euphonious",
        "exhilaratingly clear",
        "intricately layered",
        "breathtakingly immersive",
        "stunningly detailed",
        "emotionally resonant",
        "blissfully harmonious",
        "acoustically transparent",
        "artfully produced",
        "precision-crafted",
        "masterfully engineered",
        "beautifully balanced",
        "exceptionally vivid",
        "extraordinarily dynamic",
        "strikingly realistic",
        "soothing",
        "energizing",
        "comforting",
        "exhilaratingly alive",
        "transcendently expressive"
      ],
      "type": "positive"
    },
    {
      "id": "audio-quality",
      "title": "Audio quality positive list",
      "items": [
        "studio-quality",
        "hi-fidelity",
        "professionally mastered",
        "crystal-clear",
        "audiophile-grade",
        "lossless",
        "pristine",
        "clean mix",
        "balanced",
        "wide dynamic range",
        "rich stereo imaging",
        "immersive",
        "polished",
        "warm analog",
        "punchy",
        "full-spectrum",
        "lush",
        "detailed",
        "noise-free",
        "surround sound",
        "spatial",
        "vibrant",
        "dynamic",
        "articulate",
        "masterful",
        "excellent",
        "superb",
        "outstanding",
        "flawless",
        "exceptional",
        "pristine treble",
        "deep bass response",
        "tight bass",
        "silky smooth mids",
        "natural soundstage",
        "transparent",
        "airy",
        "holographic",
        "organic",
        "cohesive",
        "precise",
        "nuanced",
        "authentic",
        "rich texture",
        "lifelike realism",
        "true-to-source",
        "captivating",
        "engrossing",
        "engaging",
        "exquisite",
        "clean separation",
        "accurate imaging",
        "vivid",
        "controlled",
        "refined",
        "fluid",
        "resonant",
        "energetic",
        "well-defined",
        "well-balanced",
        "optimal fidelity",
        "billboard-level",
        "Grammy-quality",
        "definitive",
        "seamless",
        "resonating",
        "clear-cut",
        "invigorating",
        "enhanced clarity",
        "high-resolution audio",
        "sonically pleasing",
        "harmonious",
        "musicality",
        "smooth transitions",
        "perfectly tuned",
        "masterwork",
        "state-of-the-art",
        "superior",
        "compelling",
        "rich harmonics",
        "powerful dynamics",
        "precise timing",
        "impeccable"
      ],
      "type": "positive"
    },
    {
      "id": "suno",
      "title": "Suno (1000)",
      "items": [
        "1000"
      ],
      "type": "length"
    },
    {
      "id": "riffusion",
      "title": "Riffusion (10000)",
      "items": [
        "10000"
      ],
      "type": "length"
    },
    {
      "id": "base-sample",
      "title": "Empty Base Prompt",
      "items": [],
      "type": "base"
    },
    {
      "id": "lyrics-sample",
      "title": "Empty Lyrics",
      "items": [],
      "type": "lyrics"
    },
    {
      "id": "divider-simple",
      "title": "Simple",
      "items": [],
      "type": "divider"
    },
    {
      "id": "divider-natural",
      "title": "Natural",
      "items": [
        "In other words, ",
        "i.e., ",
        "Put another way, ",
        "Restated, ",
        "Which is to say, ",
        "To be precise, ",
        "In essence, ",
        "Put differently, ",
        "To put it another way, ",
        "That is to say, ",
        "Namely, ",
        "Rephrased, ",
        "To say it another way, ",
        "Let me put it this way. "
      ],
      "type": "divider"
    },
    {
      "id": "order-sample",
      "title": "Sample Order",
      "items": [
        0,
        1,
        2
      ],
      "type": "order"
    }
  ]
};
