const GENRES = [
    'alte',
    'art pop',
    'asmr',
    'avant-garde jazz',
    'background music',
    'beatboxing',
    'big room',
    'binaural',
    'ambisonic',
    'sorround sound',
    'harmonic exciter',
    'harmonic distrotion',
    'spatial audio',
    'wide-spectrum',
    'narrow-band',
    'found recording',
    'reamping',
    'brooklyn drill',
    'chopped and screwed',
    'city pop',
    'dark jazz',
    'dembow dominicano',
    'dixieland',
    'djembe',
    'exotica',
    'focus',
    'freak folk',
    'glitch beats',
    'glitch hop',
    'gypsy',
    'halloween',
    'hauntology',
    'healing',
    'heartland rock',
    'hula',
    'hurdy-gurdy',
    'hypnosis',
    'jazz saxophone',
    'mantra',
    'mashup',
    'minimalism',
    'motivation',
    'musique concrete',
    'nightcore',
    'nyckelharpa',
    'ostrock',
    'piseiro',
    'pluggnb',
    'plunderphonics',
    'reading',
    'recorder',
    'sarod',
    'sleep',
    'slushwave',
    'sound art',
    'sound collage',
    'space ambient',
    'spectra',
    'strut',
    'tabla',
    'tar',
    'tarantella',
    'therapy',
    'touhou',
    'turntablism',
    'via',
    'washboard',
    'weirdcore',
    'wonky',
    'writing',
    '2-step',
    '432hz',
    '8-bit',
    '8d',
    'a cappella',
    'abstract hip hop',
    'abstract',
    'accordeon',
    'accordion',
    'acid house',
    'acid jazz',
    'acid rock',
    'acid techno',
    'acid trance',
    'acoustic blues',
    'acoustic pop',
    'acoustic rock',
    'afro house',
    'afro r&b',
    'afro-funk',
    'afrobeat',
    'afrobeats',
    'afroswing',
    'aggressive phonk',
    'ai',
    'akordeon',
    'algorave',
    'alternative country',
    'alternative dance',
    'alternative hip hop',
    'alternative metal',
    'alternative pop rock',
    'alternative pop',
    'alternative r&b',
    'alternative rock',
    'amapiano',
    'ambient dub techno',
    'ambient fusion',
    'ambient guitar',
    'ambient house',
    'ambient lo-fi',
    'ambient pop',
    'ambient synth',
    'ambient techno',
    'ambient trance',
    'ambient',
    'anime lo-fi',
    'anime',
    'anthem',
    'anti-folk',
    'appalachian folk',
    'arabesk',
    'armenian folk',
    'art rock',
    'atmosphere',
    'australian rock',
    'avant-garde',
    'axe',
    'bachata',
    'background jazz',
    'bagpipe',
    'balalaika',
    'balkan brass',
    'ballroom',
    'banjo',
    'barbershop',
    'bard',
    'baroque pop',
    'baroque violin',
    'baroque',
    'bass house',
    'bass music',
    'bass trap',
    'bassline',
    'battle rap',
    'beach house',
    'beatdown',
    'beats',
    'bebop',
    'bedroom pop',
    'bells',
    'bgm',
    'bhajan',
    'bhangra',
    'big band',
    'big beat',
    'birthday',
    'black metal',
    'bluegrass',
    'blues rock',
    'blues',
    'bolero',
    'bomba',
    'boogie-woogie',
    'boogie',
    'boom bap',
    'bossa nova',
    'bounce',
    'bouncy house',
    'boy band',
    'boy pop',
    'brass band',
    'breakbeat',
    'breakcore',
    'breaks',
    'british folk',
    'british invasion',
    'britpop',
    'broadway',
    'brostep',
    'brutal death metal',
    'bubblegum bass',
    'bubblegum dance',
    'bubblegum pop',
    'c-pop',
    'cabaret',
    'cajun',
    'calypso',
    'candy pop',
    'cantopop',
    'carnatic',
    'cartoon',
    'cello',
    'celtic harp',
    'celtic metal',
    'celtic',
    'chanson',
    'chicago blues',
    'chill beats',
    'chill house',
    'chill lounge',
    'chill out',
    'chillhop',
    'chillstep',
    'chillsynth',
    'chillwave',
    'chinese folk',
    'chinese traditional',
    'chip hop',
    'chiptune',
    'choral',
    'christian metal',
    'christian rock',
    'circuit',
    'circus',
    'classic rock',
    'classical cello',
    'classical guitar',
    'classical piano',
    'classical',
    'cloud rap',
    'coldwave',
    'comedia',
    'comedy rap',
    'comedy rock',
    'comedy',
    'contemporary classical piano',
    'contemporary classical',
    'contemporary country',
    'contemporary r&b',
    'contrabass',
    'corrido',
    'corridos tumbados',
    'country blues',
    'country gospel',
    'country pop',
    'country rap',
    'country rock',
    'country',
    'crossover thrash',
    'crunk',
    'cuarteto',
    'cumbia',
    'cyberpunk',
    'd-beat',
    'dance pop',
    'dance rock',
    'dance-punk',
    'dancehall',
    'dangdut',
    'darbuka',
    'dark ambient',
    'dark cabaret',
    'dark electro',
    'dark folk',
    'dark pop',
    'dark rock',
    'dark techno',
    'dark trap',
    'dark wave',
    'darksynth',
    'death metal',
    'deathcore',
    'deep deep tech house',
    'deep dubstep',
    'deep funk',
    'deep house',
    'deep progressive house',
    'deep tech house',
    'deep techno',
    'delta blues',
    'dembow',
    'didgeridoo',
    'digital hardcore',
    'disco polo',
    'disco',
    'djent',
    'doo-wop',
    'doom metal',
    'doomcore',
    'doujin',
    'downtempo',
    'drain',
    'drama',
    'dream pop',
    'dreampunk',
    'drift phonk',
    'drift',
    'drill and bass',
    'drill beats',
    'drill',
    'drone metal',
    'drone',
    'drum and bass',
    'dub techno',
    'dub',
    'dubstep',
    'duduk',
    'dungeon synth',
    'east coast hip hop',
    'easy listening',
    'ebm',
    'edm',
    'electric bass',
    'electric blues',
    'electro dub',
    'electro house',
    'electro swing',
    'electro-industrial',
    'electro',
    'electroclash',
    'electronic rock',
    'electronic trap',
    'electronica',
    'electropop',
    'emo punk',
    'emo rap',
    'emo',
    'emocore',
    'enka',
    'erhu',
    'ethereal wave',
    'euphoric hardstyle',
    'eurobeat',
    'eurodance',
    'europop',
    'experimental ambient',
    'experimental electronic',
    'experimental hip hop',
    'experimental indie',
    'experimental jazz',
    'experimental pop',
    'experimental psych',
    'experimental rock',
    'experimental synth',
    'experimental',
    'fado',
    'fantasy metal',
    'fantasy',
    'field recording',
    'fife and drum',
    'filmi',
    'fingerstyle',
    'finnish tango',
    'flamenco guitar',
    'flamenco urbano',
    'flamenco',
    'folk metal',
    'folk punk',
    'folk rock',
    'folk-pop',
    'folk',
    'folktronica',
    'football',
    'footwork',
    'free folk',
    'free jazz',
    'freeform hardcore',
    'freestyle',
    'french dub',
    'french pop',
    'frenchcore',
    'funeral doom',
    'funk carioca',
    'funk metal',
    'funk pop',
    'funk rock',
    'funk',
    'funktronica',
    'future bass',
    'future funk',
    'future garage',
    'future house',
    'future rock',
    'futurepop',
    'g funk',
    'gabber',
    'gamelan',
    'gangster rap',
    'garage pop',
    'garage psych',
    'garage rock',
    'german electronica',
    'german metal',
    'german pop rock',
    'german pop',
    'german power metal',
    'german punk rock',
    'german punk',
    'german singer-songwriter',
    'german trap',
    'girl group',
    'glam metal',
    'glam rock',
    'glass',
    'glee club',
    'glitch',
    'glitchcore',
    'gnawa',
    'goa psytrance',
    'goa trance',
    'gong',
    'gospel rap',
    'gospel soul',
    'gospel',
    'gothic alternative',
    'gothic doom',
    'gothic metal',
    'gothic rock',
    'gregorian chant',
    'grime',
    'grindcore',
    'griot',
    'groove metal',
    'grunge',
    'grungegaze',
    'gumbe',
    'guqin',
    'guzheng',
    'gypsy punk',
    'hammond organ',
    'handpan',
    'happy hardcore',
    'hard bass',
    'hard dance',
    'hard rock',
    'hard trance',
    'hardcore hip hop',
    'hardcore punk',
    'hardcore techno',
    'hardcore',
    'hardstyle',
    'hardtekk',
    'harmonica blues',
    'harp',
    'harpsichord',
    'hawaiian',
    'hel',
    'hip hop',
    'hip pop',
    'honky tonk',
    'horo',
    'horror punk',
    'horror synth',
    'horrorcore',
    'hot jazz',
    'house',
    'humppa',
    'hyperpop',
    'hyphy',
    'hypnagogic pop',
    'idol',
    'illbient',
    'indie folk',
    'indie pop rock',
    'indie pop',
    'indie punk',
    'indie rock',
    'indietronica',
    'industrial metal',
    'industrial noise',
    'industrial rock',
    'industrial techno',
    'industrial',
    'instrumental bluegrass',
    'instrumental death metal',
    'instrumental rock',
    'irish folk',
    'irish punk',
    'italian opera',
    'italian pop',
    'italo disco',
    'j-core',
    'j-pop',
    'j-punk',
    'j-rap',
    'j-rock',
    'jangle pop',
    'japanese folk',
    'japanese indie pop',
    'japanese jazz',
    'japanese math rock',
    'japanese trap',
    'japanoise',
    'jazz blues',
    'jazz funk',
    'jazz fusion',
    'jazz piano',
    'jazz pop',
    'jazz rock',
    'jazz',
    'jazzcore',
    'jersey club',
    'jungle',
    'k-pop',
    'k-rap',
    'k-rock',
    'kawaii future bass',
    'kawaii metal',
    'keroncong',
    'klezmer',
    'korean musicals',
    'korean r&b',
    'koto',
    'krautrock',
    'la pop',
    'language',
    'lata',
    'latin hip hop',
    'latin house',
    'latin jazz',
    'latin pop',
    'latin rock',
    'lds',
    'levenslied',
    'light music',
    'lo-fi beats',
    'lo-fi chill',
    'lo-fi emo',
    'lo-fi house',
    'lo-fi indie',
    'lo-fi rap',
    'lo-fi',
    'lounge',
    'lowercase',
    'lullaby',
    'lute',
    'maghreb',
    'mahraganat',
    'mallsoft',
    'maloya',
    'mambo',
    'mandolin',
    'mandopop',
    'manele',
    'marching band',
    'mariachi',
    'marimba',
    'math rock',
    'mathcore',
    'mbira',
    'mecha',
    'medieval folk',
    'medieval rock',
    'medieval',
    'meditation',
    'melodic death metal',
    'melodic deathcore',
    'melodic doom',
    'melodic dubstep',
    'melodic hard rock',
    'melodic hardcore',
    'melodic metal',
    'melodic metalcore',
    'melodic rap',
    'melodic techno',
    'memphis phonk',
    'mento',
    'merengue',
    'merseybeat',
    'metal guitar',
    'metal',
    'metalcore',
    'miami bass',
    'microhouse',
    'midwest emo',
    'minimal dub',
    'minimal dubstep',
    'minimal synth',
    'minimal tech house',
    'minimal techno',
    'minimal wave',
    'mizrahi',
    'modern funk',
    'moog',
    'moombahton',
    'motown',
    'music box',
    'neo honky tonk',
    'neo soul',
    'neo-classical',
    'neo-pagan',
    'neo-rockabilly',
    'neofolk',
    'neurofunk',
    'new age',
    'new jack swing',
    'new orleans jazz',
    'new romantic',
    'new wave pop',
    'new wave',
    'ney',
    'nintendocore',
    'no beat',
    'noise',
    'nordic folk',
    'northern soul',
    'novelty',
    'nu disco',
    'nu jazz',
    'nu metal',
    'nursery',
    'ocean',
    'oi',
    'old school hip hop',
    'opera metal',
    'opera',
    'orchestra',
    'orchestral soundtrack',
    'oriental metal',
    'orthodox chant',
    'oud',
    'outsider',
    'p funk',
    'p-pop',
    'parody',
    'phonk',
    'piano cover',
    'piano rock',
    'pipa',
    'pirate',
    'pixel',
    'plugg',
    'poetry',
    'polka',
    'polyphony',
    'pop ambient',
    'pop dance',
    'pop edm',
    'pop emo',
    'pop folk',
    'pop house',
    'pop punk',
    'pop r&b',
    'pop rap',
    'pop rock',
    'pop soul',
    'pop',
    'post-disco',
    'post-grunge',
    'post-hardcore',
    'post-metal',
    'post-minimalism',
    'post-post-hardcore',
    'post-punk',
    'post-rock',
    'power metal',
    'power pop',
    'prog metal',
    'progressive bluegrass',
    'progressive house',
    'progressive metal',
    'progressive power metal',
    'progressive rock',
    'progressive trance',
    'psychedelic folk',
    'psychedelic pop',
    'psychedelic rock',
    'psychedelic soul',
    'psychedelic trance',
    'psychobilly',
    'pub rock',
    'punk blues',
    'punk ska',
    'punk',
    'punta',
    'qawwali',
    'quiet storm',
    'r&b',
    'ragga jungle',
    'ragtime',
    'rai',
    'rain',
    'ranchera',
    'rap francais',
    'rap metal',
    'rap rock',
    'rap',
    'rave',
    'rawstyle',
    'reggae',
    'reggaeton',
    'rhythm and blues',
    'rhythm rock',
    'riddim dubstep',
    'riddim',
    'rif',
    'ringtone',
    'riot grrrl',
    'rock drums',
    'rock',
    'rockabilly',
    'roots reggae',
    'rumba catalana',
    'rumba',
    'russian alt pop',
    'russian choir',
    'russian hip hop',
    'russian indie',
    'russian pop',
    'russian post-punk',
    'russian rock',
    'sad rap',
    'salsa',
    'samba',
    'sarangi',
    'schlager',
    'scratch',
    'screamo',
    'sega',
    'sertanejo',
    'shakuhachi',
    'shamanic',
    'shamisen',
    'shanty',
    'shib',
    'shoegaze',
    'show tunes',
    'shred',
    'singer-songwriter pop',
    'singer-songwriter',
    'sitar',
    'ska punk',
    'ska',
    'skate punk',
    'slap house',
    'slowcore',
    'sludge metal',
    'smooth jazz',
    'smooth soul',
    'soft rock',
    'soul blues',
    'soul jazz',
    'soul',
    'sound effects',
    'sound',
    'soundtrack',
    'southern rock',
    'soviet synthpop',
    'sovietwave',
    'spa',
    'space rock',
    'spanish blues',
    'spanish electronic',
    'spanish hip hop',
    'spanish pop',
    'spanish reggae',
    'speed metal',
    'speedcore',
    'spoken word',
    'steampunk',
    'steel guitar',
    'stoner metal',
    'stoner rock',
    'string orchestra',
    'string quartet',
    'sung poetry',
    'sunshine pop',
    'suomisaundi',
    'surf music',
    'surf punk',
    'swamp blues',
    'swancore',
    'swedish metal',
    'swedish pop',
    'swedish power metal',
    'swing',
    'symphonic black metal',
    'symphonic death metal',
    'symphonic metal',
    'symphonic power metal',
    'symphonic rock',
    'synth prog',
    'synthesizer',
    'synthpop',
    'synthwave',
    'taiko',
    'talkbox',
    'tango',
    'tavern',
    'tech house',
    'tech trance',
    'techno',
    'teen pop',
    'tekk',
    'texas blues',
    'thall',
    'theme',
    'theremin',
    'thrash metal',
    'throat singing',
    'tin pan alley',
    'tone',
    'traditional folk',
    'trance',
    'trancecore',
    'trap beats',
    'trap',
    'tribal house',
    'tribute',
    'trip hop',
    'tropical house',
    'tropical',
    'trot',
    'turkish folk',
    'turkish pop',
    'turkish rock',
    'uilleann pipes',
    'uk drill',
    'uk garage',
    'ukulele',
    'umea hardcore',
    'underground rap',
    'uptempo hardcore',
    'vaporwave',
    'viking metal',
    'viola',
    'violin',
    'visual kei',
    'vocal house',
    'vocal jazz',
    'vocal trance',
    'vocaloid',
    'vocoder',
    'vogue',
    'volksmusik',
    'water',
    'wave',
    'west coast rap',
    'witch house',
    'world',
    'worship',
    'yacht rock',
    'yodeling',
    'yoga',
    'zen',
    'zouk',
];
