/**
 * Positive modifier lists for prompt generation
 * Each list includes a title and the actual list items
 */
const POSITIVE_LISTS = {
  // List of available presets with titles and data
  presets: [
    {
      id: 'empty',
      title: 'Empty positive list',
      items: []
    },
    {
      id: 'image-positive',
      title: 'Image positive list',
      items: [
        "masterpiece",
        "best quality",
        "high quality",
        "top quality",
        "highest quality",
        "ultra high quality",
        "very aesthetic",
        "aesthetic",
        "beautiful",
        "beautiful and aesthetic",
        "good",
        "great",
        "best",
        "beautiful",
        "newest",
        "2023",
        "2022",
        "2021",
        "depth of field",
        "DOF",
        "bokeh",
        "8k",
        "8k resolution",
        "8k wallpaper",
        "4k",
        "4k resolution",
        "UHD",
        "HD",
        "highres",
        "absurdres",
        "ultra high definition",
        "high definition",
        "detailed",
        "highly detailed",
        "very detailed",
        "extremely detailed",
        "ultra detailed",
        "incredibly detailed",
        "hyper detailed",
        "intricate",
        "intricate details",
        "finely detailed",
        "sharp focus",
        "in focus",
        "focused",
        "detailed shadows",
        "detailed background",
        "detailed clothing",
        "detailed eyes",
        "beautiful eyes",
        "vibrant colors",
        "vivid colors",
        "rich colors",
        "colorful",
        "bright colors",
        "volumetric",
        "god rays",
        "lens flare",
        "bloom",
        "ambient occlusion",
        "official",
        "dynamic",
        "detailed skin",
      "detailed skin texture",
      ]
    },
    {
      id: 'general-audio',
      title: 'General audio positive list',
      items: [
        "good",
        "best",
        "great",
        "wonderful",
        "amazing",
        "incredible",
        "stunning",
        "beautiful",
        "brilliant",
        "genius",
        "complex",
        "intricate",
        "layered",
        "lush",
        "expansive",
        "frisson",
        "powerful",
        "moving",
        "brought to tears by",
        "sublime",
        "breathtaking",
        "mesmerizing",
        "awe-inspiring",
        "evocative",
        "profound",
        "exquisite",
        "dazzling",
        "sensational",
        "haunting",
        "captivating",
        "enchanting",
        "masterful",
        "poignant",
        "spellbinding",
        "transcendent",
        "majestic",
        "ethereal",
        "phenomenal",
        "vibrant",
        "exhilarating",
        "radiant",
        "luminous",
        "stirring",
        "magnificent",
        "extraordinary",
        "unparalleled",
        "unforgettable",
        "transformative",
        "euphoric",
        "enthralling",
        "heartfelt",
        "soul-stirring",
        "groundbreaking",
        "iconic",
        "visionary",
        "astonishing",
        "compelling",
        "nuanced",
        "thought-provoking",
        "resonant",
        "cathartic",
        "thrilling",
        "expressive",
        "virtuosic",
        "electrifying",
        "tender",
        "graceful",
        "delicate",
        "vivid",
        "intricate",
        "imaginative",
        "emotive",
        "rapturous",
        "dynamic",
        "balanced",
        "immersive",
        "crystalline",
        "resonant",
        "lushly orchestrated",
        "harmonically rich",
        "sonorous",
        "pristine",
        "textured",
        "atmospheric",
        "detailed",
        "nuanced",
        "spatially expansive",
        "warm",
        "inviting",
        "enveloping",
        "engaging",
        "lifelike",
        "rhythmic",
        "percussive",
        "robust",
        "smooth",
        "velvety",
        "silky",
        "refined",
        "natural",
        "transparent",
        "punchy",
        "crisp",
        "vivid",
        "evocative",
        "spine-tingling",
        "goosebump-inducing",
        "emotionally charged",
        "deeply affecting",
        "blissful",
        "hypnotic",
        "melodic",
        "pulsating",
        "groovy",
        "euphonious",
        "exhilaratingly clear",
        "intricately layered",
        "breathtakingly immersive",
        "stunningly detailed",
        "emotionally resonant",
        "blissfully harmonious",
        "acoustically transparent",
        "artfully produced",
        "precision-crafted",
        "masterfully engineered",
        "beautifully balanced",
        "exceptionally vivid",
        "extraordinarily dynamic",
        "strikingly realistic",
        "soothing",
        "energizing",
        "comforting",
        "exhilaratingly alive",
        "transcendently expressive",
      ]
    },
  ]
};
